/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import {
  useMutation
} from 'react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from 'react-query';

import type {
  PostListValidateTokensBody,
  ResUser
} from '../../../domain/types/v1api';

import { orvalAxiosInstance } from '../../orval/orval-axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Add new
 */
export const postListValidateTokens = (
    postListValidateTokensBody: PostListValidateTokensBody,
 options?: SecondParameter<typeof orvalAxiosInstance>,signal?: AbortSignal
) => {
      
      
      return orvalAxiosInstance<ResUser>(
      {url: `/api/v1/validateTokens/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postListValidateTokensBody, signal
    },
      options);
    }
  


export const getPostListValidateTokensMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListValidateTokens>>, TError,{data: PostListValidateTokensBody}, TContext>, request?: SecondParameter<typeof orvalAxiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postListValidateTokens>>, TError,{data: PostListValidateTokensBody}, TContext> => {

const mutationKey = ['postListValidateTokens'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postListValidateTokens>>, {data: PostListValidateTokensBody}> = (props) => {
          const {data} = props ?? {};

          return  postListValidateTokens(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostListValidateTokensMutationResult = NonNullable<Awaited<ReturnType<typeof postListValidateTokens>>>
    export type PostListValidateTokensMutationBody = PostListValidateTokensBody
    export type PostListValidateTokensMutationError = unknown

    export const usePostListValidateTokens = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postListValidateTokens>>, TError,{data: PostListValidateTokensBody}, TContext>, request?: SecondParameter<typeof orvalAxiosInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postListValidateTokens>>,
        TError,
        {data: PostListValidateTokensBody},
        TContext
      > => {

      const mutationOptions = getPostListValidateTokensMutationOptions(options);

      return useMutation(mutationOptions);
    }
    