import { defineConfig } from "orval"

// Mirrors the host repo's orval setup, but scoped to the ranking endpoints only.
// Each repo generates and commits its own copy of the client/types (mostly
// types) from the live OpenAPI spec — there is no shared api-client package.
export default defineConfig({
  v1api: {
    output: {
      namingConvention: "camelCase",
      target: "src/infrastructure/repositories/v1api.ts",
      schemas: "src/domain/types/v1api",
      mode: "tags-split",
      prettier: true,
      client: "react-query",
      allParamsOptional: false,
      propertySortOrder: "Alphabetical",
      override: {
        header: (info) => [
          "Generated by orval. Do not edit manually.",
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
        ],
        query: {
          useQuery: true,
          usePrefetch: true,
        },
        mutator: {
          path: "./src/infrastructure/orval/orval-axios-instance.ts",
          name: "orvalAxiosInstance",
        },
      },
    },
    input: {
      // The ranking CRUD endpoints currently live only on the LOCAL backend.
      // Switch this to the deployed spec (https://www.oreplay.es/api/v1/openapi/json)
      // once they ship to production.
      target: "http://localhost/api/v1/openapi/json",
      filters: {
        mode: "include",
        tags: [/Ranking/, /Events/, /Stages/],
      },
    },
  },
})
