/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { Organizer } from "./organizer"

/**
 * Data wrapper for Organizer
 */
export interface ArrayOrganizer {
  data: Organizer[]
}
