/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { StatsInClass } from "./statsInClass"

/**
 * Data wrapper for StatsInClass
 */
export interface ArrayStatsInClass {
  data: StatsInClass[]
}
