/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { RunnerSearch } from "./runnerSearch"

/**
 * Data wrapper for RunnerSearch
 */
export interface ArrayRunnerSearch {
  data: RunnerSearch[]
}
