/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { ControlType } from "./controlType"

/**
 * Entity Control
 */
export interface Control {
  control_type: ControlType
  id: string
  station: number
}
