/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { Stats } from "./stats"

/**
 * Entity GenderGrouped
 */
export interface GenderGrouped {
  any?: Stats
  F?: Stats
  M?: Stats
}
