/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */

export type GetListFedoStatsParams = {
  officialSeniorM?: string
  officialSeniorF?: string
  officialSub20M?: string
  officialSub20F?: string
}
