/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { PartialOverall } from "./partialOverall"

/**
 * Entity Overalls
 */
export interface Overalls {
  overall?: PartialOverall
  parts?: PartialOverall[]
}
