/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { PaginationLinks } from "./paginationLinks"
import type { Event } from "./event"

/**
 * Paginated Event
 */
export interface PaginatedEvent {
  _links: PaginationLinks
  data: Event[]
  limit: number
  total: number
}
