/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { PaginationLinksNext } from "./paginationLinksNext"
import type { PaginationLinksPrev } from "./paginationLinksPrev"
import type { PaginationLinksSelf } from "./paginationLinksSelf"

/**
 * Pagination links.
 */
export interface PaginationLinks {
  /** Generic object. */
  next?: PaginationLinksNext
  /** Generic object. */
  prev?: PaginationLinksPrev
  /** Generic object. */
  self?: PaginationLinksSelf
}
