/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */

/**
 * Entity PatchStageOrdersBody
 */
export interface PatchStageOrdersBody {
  description: string
}
