/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */

/**
 * Entity PatchStagesBody
 */
export interface PatchStagesBody {
  description?: string
  stage_type_id?: string
  state_end?: number
}
