/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { PdfElement } from "./pdfElement"

/**
 * Entity PdfSection
 */
export interface PdfSection {
  elements: PdfElement[]
}
