/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */

/**
 * Generic object when: Add new
 */
export type PostListEventTokensBody = {
  expires?: string
}
