/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */

/**
 * Generic object when: Add new
 */
export type PostListEventsBody = {
  description?: string
  federation_id?: string
  final_date?: string
  id?: string
  initial_date?: string
  organizer_id?: string
}
