/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */

/**
 * Entity RankingOrganizer
 */
export interface RankingOrganizer {
  created: string
  /** @nullable */
  description?: string | null
  first_name: string
  id: string
  last_name: string
  modified: string
  /** @nullable */
  runner_id?: string | null
  stage_order_id: string
}
