/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { LinkHref } from "./linkHref"

/**
 * Entity RankingLinks
 */
export interface RankingLinks {
  results?: LinkHref
  self?: LinkHref
}
