/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { ClassEntity } from "./classEntity"

/**
 * Data wrapper for ClassEntity
 */
export interface ResClassEntity {
  data: ClassEntity
}
