/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { Event } from "./event"

/**
 * Data wrapper for Event
 */
export interface ResEvent {
  data: Event
}
