/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { RawUpload } from "./rawUpload"

/**
 * Data wrapper for RawUpload
 */
export interface ResRawUpload {
  data: RawUpload
}
