/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { Ranking } from "./ranking"

/**
 * Data wrapper for Ranking
 */
export interface ResRanking {
  data: Ranking
}
