/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { RankingOrganizer } from "./rankingOrganizer"

/**
 * Data wrapper for RankingOrganizer
 */
export interface ResRankingOrganizer {
  data: RankingOrganizer
}
