/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { Result } from "./result"

/**
 * Data wrapper for Result
 */
export interface ResResult {
  data: Result
}
