/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { Stage } from "./stage"

/**
 * Data wrapper for Stage
 */
export interface ResStage {
  data: Stage
}
