/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { User } from "./user"

/**
 * Data wrapper for User
 */
export interface ResUser {
  data: User
}
