/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { ResUploadedData } from "./resUploadedData"
import type { UploadedMeta } from "./uploadedMeta"

/**
 * Data wrapper for ResUploaded
 */
export interface ResUploaded {
  /** Any object */
  data: ResUploadedData
  meta?: UploadedMeta
}
