/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { Control } from "./control"

/**
 * Entity Split
 */
export interface Split {
  control?: Control
  created?: string
  id: string
  is_intermediate?: boolean
  /** @nullable */
  order_number?: string | null
  /** @nullable */
  points?: string | null
  reading_time?: string
  station?: number
}
