/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */

/**
 * Entity StageOrderManagement
 */
export interface StageOrderManagement {
  created: string
  description: string
  id: string
  stage_order: number
}
