/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { LinkHref } from "./linkHref"

/**
 * Entity StageLinks
 */
export interface StageLinks {
  classes?: LinkHref
  results?: LinkHref
  self?: LinkHref
}
