/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */

/**
 * Entity Token
 */
export interface Token {
  created?: string
  expires?: string
  token?: string
}
