/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */

/**
 * Generic object.
 */
export type UploadedV2MetaUpdated = {
  classes?: number
  courses?: number
  runnerResults?: number
  runners?: number
  splits?: number
}
