/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */

/**
 * Generic object.
 */
export type UploadDataTransferConfiguration = {
  contents?: string
  results_type?: string
  source?: string
  source_vendor?: string
  source_version?: number
  utf?: number
}
