/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */

/**
 * objectInArray
 */
export type UploadedV2MetaTimingsProcessingRunners = {
  clubs?: number
  runnerLoop?: number
  runnerResults?: number
  runnersInLoop?: number
  splits?: number
  total?: number
}
