/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { UploadDataTransferEventStagesItem } from "./uploadDataTransferEventStagesItem"

/**
 * Generic object.
 */
export type UploadDataTransferEvent = {
  description?: string
  id?: string
  stages?: UploadDataTransferEventStagesItem[]
}
