/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */
import type { UploadDataTransfer } from "./uploadDataTransfer"

/**
 * Entity UploadPostData
 */
export interface UploadPostData {
  oreplay_data_transfer: UploadDataTransfer
}
