/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 */

/**
 * Entity User
 */
export interface User {
  created?: string
  email: string
  first_name: string
  id: string
  last_name: string
  modified?: string
  scope?: string
}
